### ISSUE TITLE
Cover Size

### ISSUE THREAD

**Issue by lionelsam** [raywo/MMM-NowPlayingOnSpotify#21]
how can i change the cover Art size when showCovertArt is true

**Comment by aaronmaynard** [comment]
In `modules/MMM-NowPlayingOnSpotify/css/styles.css` you can change how the module looks.  I recommend staying with percentages rather than in pixels to maintain your ratios during scaling.

In my example you can see that I changed the album cover to 80% width.  Adjust this to your liking.  If you need help with how CSS works, I highly recommend looking through the W3Schools site.

![nowplayingonspotify](https://user-images.githubusercontent.com/34851708/41117551-fc9bf9d0-6a52-11e8-8b91-7ece8607f28d.jpg)
